id: P5BE54056
initial_creation_type: input
source_metadata:
  title: 'Vasubandhu: Triṃśikāvijñapti'
  language: sa
  volumes:
    6dff5ecf353745558d7bedc02b333d85:
      title: CI_Verses 1-10
      base_file: CI_Verses 1-10.txt
      work_id: WFD810C9F
    7eef8ea39f2945779b50026133bab523:
      title: CI_Verses 11-20
      base_file: CI_Verses 11-20.txt
      work_id: W343883C8
    957b8f15696a4ad19ddcf6b3fea65ec9:
      title: CI_Verses 21-31
      base_file: CI_Verses 21-31.txt
      work_id: W1594B3F8
  chapter_to_tile:
    CI: Title
created_at: '2022-03-01T23:28:05.507335'
last_modified_at: '2022-03-01T23:28:05.507342'
